### ISSUE TITLE
Not readable text @ front page

### ISSUE THREAD

**Issue by nofutur3** [vpsfreecz/web#2]
Main text in header is not readable - Firefox (latest), full HD.

![vpsfree cz virtualni privatni servery svobodne 2016-06-09 09-45-44](https://cloud.githubusercontent.com/assets/1681221/15923101/88d1d052-2e2b-11e6-8c15-b474909280b5.png)

**Comment by aither64** [comment]
Je uz to lepsi? Mne se to teda zobrazovalo ve FF vzdycky dobre, ale nejake zmatky s fontama tam byly.
