### ISSUE TITLE
Login do administrace

### ISSUE THREAD

**Issue by landsman** [vpsfreecz/web#4]
Ahoj,

docela mi chybí login do [správy VPS](https://vpsadmin.vpsfree.cz/) přímo z [webu](https://vpsfree.cz),
co na to říkáte?

Kam by jste ho případně umístili? Ideální by bylo hl. menu.

**Comment by sorki** [comment]
Hoj, dobra otazka kam to dat :)

Mne prislo, ze link na kb.vpsf je moc zasity v tom prvom submenu ale nevymyslel som kam s tym. Inak +1

**Comment by aither64** [comment]
@petrkrcmar kam to dame?

**Comment by petrkrcmar** [comment]
Co takhle přidat další submenu „Pro členy“ a tam hodit KB i vpsAdmina?

**Comment by aither64** [comment]
Viz https://dev.vpsfree.cz a https://dev.vpsfree.org. Je to ok? Link do KB je tam teda 2x (O vpsfree a pro cleny), ale myslim, ze to neni na skodu...

**Comment by petrkrcmar** [comment]
Jo, mně se to líbí. Ale tu první bázi bych vyhodil, ne?

**Comment by aither64** [comment]
Ok, nasazeno.

@petrkrcmar no premyslel jsem tak, ze link do KB se hodi i pro zajemce, aby videli do ceho jdou, ne jen pro stavajici cleny.

@landsman diky za nahlaseni
