### ISSUE TITLE
Link to issue only vpsadmin

### ISSUE THREAD

**Issue by smejdil** [vpsfreecz/web#9]
https://kb.vpsfree.cz/informace/chyby_a_napady

Chtelo by to pridat i link na vpsadminos :-( Zalozil jsem issue tykajici se vpsadminos do vpsadmin.

Drobna uprava webu ...

**Comment by aither64** [comment]
Promiň, tahle issue mě asi nějak minula. Pokud jsi měl na mysli přidat link na vpsAdminOS na tu stránku do KB, tak to jsem udělal. Do KB se jde přihlásit jako do vpsAdminu, upravovat ji mohou všichni členové.
